# Generated by Django 4.1.1 on 2022-11-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Stock_XS', models.IntegerField(default=0)),
                ('Stock_S', models.IntegerField(default=0)),
                ('Stock_M', models.IntegerField(default=0)),
                ('Stock_L', models.IntegerField(default=0)),
                ('Stock_XL', models.IntegerField(default=0)),
                ('Featured', models.BooleanField()),
                ('Jumper_Jacket', models.BooleanField()),
                ('Shirt', models.BooleanField()),
                ('Pants', models.BooleanField()),
                ('Shoes', models.BooleanField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
